name: yundera
services:

  admin:
    image: nasselle/settings-center-app:latest
    container_name: admin
    hostname: admin
    restart: unless-stopped
    environment:
      AUTHORITY_ENDPOINT: "https://8080-casaos-%DOMAIN%/v1/users"
    volumes:
      - type: bind
        source: /DATA/AppData/casaos/apps/yundera/
        target: /app/compose
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    expose:
      - "80"
    networks:
      pcs: null

  casaos:
    image: nasselle/casa-img:latest
    container_name: casaos
    hostname: casaos
    restart: unless-stopped
    environment:
      DATA_ROOT: "/DATA"
      REF_DOMAIN: "%DOMAIN%"
      REF_NET: "pcs"
      REF_PORT: "443"
      REF_SCHEME: "https"
      user: "%DEFAULT_USER%"
      default_pwd: "%DEFAULT_PWD%"
      public_ip: "%PUBLIC_IP%"
    networks:
      pcs: null
    volumes:
      - type: bind
        source: /DATA
        target: /DATA
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  mesh-router:
    image: nasselle/mesh-router:latest
    container_name: mesh-router
    hostname: mesh-router
    restart: unless-stopped
    environment:
      - PROVIDER=%PROVIDER_STR%
    networks:
      pcs: null
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"

networks:
  pcs:
    name: pcs

x-casaos:
  main: admin
  author: self
  category: self
  hostname: admin-%DOMAIN%
  icon: https://styles.redditmedia.com/t5_deqw76/styles/communityIcon_mrihspifrgee1.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: yundera
  title:
    custom: Yundera
